service: serverless-multiples-services-users
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: users.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
