service: serverless-multiples-services-posts
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: posts.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline